version: '3.8'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - redis
  redis:
    image: 'redis:6.2'
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

volumes:
  redis-data:
