version: '3.9'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - REDIS_HOST=redis
      - AUTH_USER=ABC
      - AUTH_PASSWORD=321
      - MAIL_USER=MichaelZaslavsky2@gmail.com
      - MAIL_PASS=abcdefghjjjkwe
      - MAIL_HOST=smtp.gmail.com
    depends_on:
      - redis

  redis:
    image: 'redis:6.2'
    ports:
      - '6379:6379'

  test:
    build: .
    command: npm test
    environment:
      - REDIS_HOST=redis
      - AUTH_USER=ABC
      - AUTH_PASSWORD=321
      - MAIL_USER=MichaelZaslavsky2@gmail.com
      - MAIL_PASS=abcdefghjjjkwe
      - MAIL_HOST=smtp.gmail.com
    depends_on:
      - redis