version: '3.9'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

  redis:
    image: 'redis:6.2'
    ports:
      - '6379:6379'

  test:
    build: .
    command: npm test
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis