name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Run tests with docker-compose
        run: |
          docker-compose up -d
          docker-compose run test
          docker-compose down
        env:
          AUTH_USER: ${{ secrets.AUTH_USER }}
          AUTH_PASSWORD: ${{ secrets.AUTH_PASSWORD }}
          MAIL_USER: ${{ secrets.MAIL_USER }}
          MAIL_PASS: ${{ secrets.MAIL_PASS }}
          MAIL_HOST: ${{ secrets.MAIL_HOST }}
          REDIS_HOST: ${{ secrets.REDIS_HOST }}
